# Generated by Django 4.2.3 on 2023-07-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('Delivery To DHL Office', 'dhl_office'), ('Express Delivery To DHL Office', 'dhl_express_office'), ('To Address', 'to_address')], default='To Address', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'cash_on_delivery'), ('Stripe', 'stipe')], default='Cash On Delivery', max_length=16),
        ),
    ]
