# Generated by Django 4.2.3 on 2023-07-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_comment_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('dhl_office', 'Delivery To DHL Office'), ('dhl_express_office', 'Express Delivery To DHL Office'), ('to_address', 'To Address')], default='To Address', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash On Delivery'), ('stipe', 'Stripe')], default='Cash On Delivery', max_length=16),
        ),
    ]
