# Generated by Django 4.2.3 on 2023-07-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash On Delivery'), ('stripe', 'Stripe')], default='Cash On Delivery', max_length=16),
        ),
    ]
